general_cfg:
  adversarial_batch_size: 128
  adversarial_epochs: 5
  algo_name: GAIL
  batch_size: 2048
  device: cuda
  discount: 0.99
  env_name: CartPole-v1
  eval_eps: 10
  eval_per_episode: 5
  hidden_dim: 32
  imitation_replay_size: 4
  load_checkpoint: false
  load_path: Collect_CartPole-v1_PPO_20221206-173222
  lr: 0.001
  max_steps: 200
  mode: train
  new_step_api: true
  num_workers: 8
  ppo_epochs: 5
  r1_reg_coeff: 1
  render: false
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 1500
  wrapper: null
algo_cfg:
  actor_hidden_dim: 256
  actor_lr: 0.0003
  batch_size: 2048
  critic_hidden_dim: 256
  critic_lr: 0.0003
  entropy_coef: 0.01
  eps_clip: 0.2
  gamma: 0.99
  k_epochs: 4
  update_freq: 2048
