general_cfg:
  algo_name: PPO
  device: cuda
  env_name: CartPole-v1
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: false
  load_path: Train_CartPole-v1_PPO-KL_20221206-054757
  max_steps: 200
  mode: train
  new_step_api: true
  render: false
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 200
  wrapper: null
algo_cfg:
  actor_hidden_dim: 256
  actor_lr: 0.0003
  continuous: false
  critic_hidden_dim: 256
  critic_lr: 0.001
  entropy_coef: 0.01
  eps_clip: 0.2
  gamma: 0.99
  k_epochs: 4
  kl_alpha: 2
  kl_beta: 1.5
  kl_lambda: 0.5
  kl_target: 0.01
  ppo_type: kl
  sgd_batch_size: 64
  train_batch_size: 100
