general_cfg:
  algo_name: DQN_CNN
  device: cuda
  env_name: Breakout-v4
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: false
  load_path: Train_Mario_DQN_CNN_20221205-205203
  max_steps: 1000
  mode: train
  new_step_api: true
  render: false
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 200
  wrapper: envs.wrappers.MarioWrappers
algo_cfg:
  batch_size: 64
  buffer_size: 100000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.99
  lr: 0.0001
  target_update: 4
