#!/usr/bin/env python
# coding=utf-8
'''
Author: GuoShiCheng
Email: guoshichenng@gmail.com
Date: 2022-12-10 08:26:17
LastEditor: GuoShiCheng
LastEditTime: 2022-12-10 08:26:17
Discription: 
Environment: python 3.7.7
'''

'''
Author: John
Email: johnjim0816@gmail.com
Date: 2020-09-11 23:03:00
LastEditor: John
LastEditTime: 2022-11-28 16:04:26
Discription: use defaultdict to define Q table
Environment: 
'''
import numpy as np
import math
import torch
import random
from collections import defaultdict


class Agent(object):
    def __init__(self,cfg):
        self.n_actions = cfg.n_actions 
        self.exploration_type = 'e-greedy' # e-greedy, boltzmann, softmax, ucb etc.
        self.lr = cfg.lr 
        self.gamma = cfg.gamma    
        self.epsilon = cfg.epsilon_start
        self.sample_count = 0  
        self.epsilon_start = cfg.epsilon_start
        self.epsilon_end = cfg.epsilon_end
        self.epsilon_decay = cfg.epsilon_decay
        self.Q_table = defaultdict(lambda: np.zeros(self.n_actions)) # use nested dictionary to represent Q(s,a), here set all Q(s,a)=0 initially, not like pseudo code
        self.n_planning = cfg.n_planning
        self.model = dict()  # environment model

    def sample_action(self, state):
        ''' sample action with e-greedy policy while training
        '''
        if self.exploration_type == 'e-greedy':
            action = self._epsilon_greedy_sample_action(state)
        else:
            raise NotImplementedError
        return action

    def predict_action(self,state):
        ''' predict action while testing 
        '''
        if self.exploration_type == 'e-greedy':
            action = self._epsilon_greedy_predict_action(state)
        else:
            raise NotImplementedError
        return action

    def _epsilon_greedy_sample_action(self, state):
        self.sample_count += 1
        # epsilon must decay(linear,exponential and etc.) for balancing exploration and exploitation
        self.epsilon = self.epsilon_end + (self.epsilon_start - self.epsilon_end) * \
            math.exp(-1. * self.sample_count / self.epsilon_decay) 
        if np.random.uniform(0, 1) > self.epsilon:
            action = np.argmax(self.Q_table[str(state)]) # choose action corresponding to the maximum q value
        else:
            action = np.random.choice(self.n_actions) # choose action randomly
        return action

    def _epsilon_greedy_predict_action(self,state):
        action = np.argmax(self.Q_table[str(state)])
        return action

    def _update_q_table(self, state, action, reward, next_state, done):
        Q_predict = self.Q_table[str(state)][action] 
        if done: # terminal state
            Q_target = reward  
        else:
            Q_target = reward + self.gamma * np.max(self.Q_table[str(next_state)]) 
        self.Q_table[str(state)][action] += self.lr * (Q_target - Q_predict)

    def update(self, state, action, reward, next_state, done):
        """
        update environment model and q_table
        """
        self._update_q_table(state, action, reward, next_state, done)
        self.model[(state, action)] = reward, next_state  # update environment model(add data into environment model)
        # Update the q-table with data generated by the environment model
        for _ in range(self.n_planning):
            # Randomly select a state action pair that has been generated by the environment model
            (state, action), (reward, next_state) = random.choice(list(self.model.items()))
            self._update_q_table(state, action, reward, next_state, done)

    def save_model(self,path):
        import dill
        from pathlib import Path
        # create path
        Path(path).mkdir(parents=True, exist_ok=True)
        torch.save(
            obj=self.Q_table,
            f=path+"DynaQ_model.pkl",
            pickle_module=dill
        )
        print("Model saved!")

    def load_model(self, path):
        import dill
        self.Q_table =torch.load(f=path+'DynaQ_model.pkl',pickle_module=dill)
        print("Mode loaded!")