general_cfg:
  algo_name: TD3
  device: cuda
  env_name: HalfCheetah-v2
  eval_eps: 5
  eval_per_episode: 10
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  max_steps: 1000
  mode: train
  new_step_api: true
  render: false
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 1200
  wrapper: null
algo_cfg:
  actor_hidden_dim: 256
  actor_lr: 0.0005
  batch_size: 256
  buffer_size: 1000000
  critic_hidden_dim: 256
  critic_lr: 0.0005
  expl_noise: 0.1
  explore_steps: 10000
  gamma: 0.99
  noise_clip: 0.5
  policy_freq: 2
  policy_noise: 0.2
  tau: 0.005

