general_cfg:
  algo_name: QLearning
  device: cpu
  env_name: CliffWalking-v0
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  max_steps: 100
  mode: train
  new_step_api: true
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 300
  wrapper: envs.wrappers.CliffWalkingWapper
algo_cfg:
  epsilon_decay: 300
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.99
  lr: 0.1
