general_cfg:
  algo_name: QLearning
  device: cpu
  env_name: FrozenLakeNoSlippery-v1
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: true
  load_path: Train_FrozenLakeNoSlippery-v1_QLearning_20221128-152949
  max_steps: 200
  mode: test
  new_step_api: true
  render: true
  render_mode: human
  save_fig: true
  seed: 10
  show_fig: false
  test_eps: 10
  train_eps: 800
  wrapper: null
algo_cfg:
  epsilon_decay: 2000
  epsilon_end: 0.1
  epsilon_start: 0.7
  gamma: 0.95
  lr: 0.9
