general_cfg:
  algo_name: SAC
  device: cpu
  env_name: Pendulum-v1
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  max_steps: 200
  mode: train
  new_step_api: true
  render: false
  save_fig: true
  seed: 10
  show_fig: false
  test_eps: 10
  train_eps: 400
  wrapper: null
algo_cfg:
  alpha: 0.2
  automatic_entropy_tuning: false
  batch_size: 64
  buffer_size: 1000000
  continous: false
  gamma: 0.99
  hidden_dim: 64
  lr: 0.001
  n_epochs: 1
  policy_type: Gaussian
  start_steps: 10000
  target_update_fre: 1
  tau: 0.005
