general_cfg:
  algo_name: QLearning
  device: cpu
  env_name: Racetrack-v0
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: true
  load_path: Train_Racetrack-v0_QLearning_20221128-154935
  max_steps: 200
  mode: test
  new_step_api: true
  render: true
  render_mode: human
  save_fig: true
  seed: 10
  show_fig: false
  test_eps: 20
  train_eps: 400
  wrapper: null
algo_cfg:
  epsilon_decay: 300
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.9
  lr: 0.1
